[versions]
androidx-lifecycle = "2.9.1"
composeHotReload = "1.0.0-alpha11"
composeMultiplatform = "1.8.2"
compose-icons = "1.6.10"
compose-navigation ="2.9.0-beta03"
compose-viewmodel = "2.9.1"

junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"

coroutinesVersion = "1.10.2"
dateTimeVersion = "0.6.2"
koin = "3.2.0"
koin-compose ="4.1.0"
ktor = "3.2.2"
sqlDelight = "2.1.0"
lifecycleViewmodelCompose = "2.7.0"
#material3 = "1.2.0"

javacv = "1.5.12"
opencv = "4.11.0-1.5.12"
patternloader ="2.4.9-7"
openpnp = "4.5.1-2"
skiko-awt = "0.9.16"
#google-fonts = "1.6.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "compose-icons" }
compose-navigation = {group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref ="compose-navigation"}
compose-lifecycle-viewmodel = {group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel"}
#google-fonts = {group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "google-fonts"}

#android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
#koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }
#koin-compose-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "dateTimeVersion" }
#ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
#ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqldelight-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
#androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref="material3" }

#for dekstop
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-java = {group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }


#https://insert-koin.io/docs/reference/koin-mp/kmp

java-cv-platform = {group = "org.bytedeco", name = "javacv-platform", version.ref = "javacv"}
java-cv = {group = "org.bytedeco", name="javacv", version.ref = "javacv"}
open-cv = {group = "org.bytedeco", name="opencv-platform", version.ref = "opencv"}
pattern-loader-opencv = { group = "nu.pattern", name = "opencv", version.ref = "patternloader" }
#open-pnp = {group = "org.openpnp", name = "opencv", version.ref = "openpnp"}
skiko-awt-runtime = {group = "org.jetbrains.skiko", name = "skiko-awt-runtime", version.ref = "skiko-awt"}

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }